import Head from "next/head";

import { Dashboard, AuthRedirect } from "~/components/layouts";

export default function DashboardPage() {
  return (
    <AuthRedirect>
      {/* <Head>
        <title>Habit Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head> */}

      <Dashboard />
    </AuthRedirect>
  );
}
